### PR TITLE
Used debouncing, fixed empty-search issue, added prettier

### PR DESCRIPTION
**Pull request by kamilkisiela**
Instead of doing a request per keystroke, we do 1 per query.

**Before**
Zrzut ekranu 2021-05-24 o 16 52 46

**After**
Zrzut ekranu 2021-05-24 o 16 55 32

### CODE REVIEW

**Review by dotansimha — APPROVED** [review]

**Comment by kamilkisiela** [comment]
Empty searches are not covered by this PR, only reduction of outgoing requests to Algolia @dotansimha

**Comment by entbit** [comment]
Looks fine to me :) @kamilkisiela could you just revert double quotes to single ones? Looks like the project is lacking a prettier config, I'll add it later.

**Comment by kamilkisiela** [comment]
@dotansimha @entbit Fixed na issue with empty search (it was a source of 75% of all searches). Now when the modal window is opened, there are no calls to Algolia API.

Plus, added prettier and ESLint checks on pre-commit hook.

**Comment by kamilkisiela** [comment]
Zrzut ekranu 2021-05-24 o 17 49 10

Last 30+ requests are empty-queries

**Pull request merged**
